# Generated by Django 4.0.1 on 2022-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_maj',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
