# Generated by Django 4.0.1 on 2022-01-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_date_maj_alter_article_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
