# Generated by Django 4.0.1 on 2022-01-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='miniature',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
