# Generated by Django 4.0.1 on 2022-01-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_miniature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='miniature',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
