# Generated by Django 4.0.1 on 2022-01-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_miniature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='contenu',
            new_name='apropos',
        ),
        migrations.AddField(
            model_name='description',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='description',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
