# Generated by Django 4.0.1 on 2022-01-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_contenu_description_apropos_description_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='auteur',
        ),
    ]
