# Generated by Django 4.0.1 on 2022-01-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('bio', models.ImageField(blank=True, upload_to='images')),
                ('email', models.EmailField(max_length=150)),
                ('password1', models.CharField(max_length=150)),
                ('password2', models.CharField(max_length=150)),
            ],
        ),
    ]
