# Generated by Django 4.0.1 on 2022-02-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUser',
        ),
    ]
